create table users (
  id uuid references auth.users not null primary key,
  name text,
  email text,
  username text unique,
  avatar_url text,
  created_at timestamp with time zone default now()
);

create table groups (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now(),
  created_by uuid references auth.users not null
);

create table group_members (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade,
  user_id uuid references auth.users not null,
  unique(group_id, user_id)
);

create table expenses (
  id bigint generated by default as identity primary key,
  paid_by uuid references auth.users not null,
  amount decimal(10,2) not null,
  description text not null,
  group_id bigint references groups(id) on delete cascade,
  receipt_url text,
  created_at timestamp with time zone default now()
);

alter table users enable row level security;
alter table groups enable row level security;
alter table group_members enable row level security;
alter table expenses enable row level security;